version: '3.8'

services:
  service.test-template:
    image: test-template:latest
    container_name: test-template
    networks:
      basic-net:
        ipv4_address: 10.0.0.10
    user: root
    depends_on: 
      - service.order

  service.order:
    image: order:latest
    container_name: order
    hostname: order
    networks:
      basic-net:
        ipv4_address: 10.0.0.11
    depends_on: 
      - infra.postgres
      - infra.nats

  service.payment:
    image: payment:latest
    container_name: payment
    hostname: payment
    networks:
      basic-net:
        ipv4_address: 10.0.0.12
    depends_on: 
      - infra.nats
      - infra.stripe-mock

  infra.postgres: 
    image: docker.io/postgres:16
    container_name: postgres
    hostname: postgres
    networks:
      basic-net:
        ipv4_address: 10.0.0.13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=guergabo
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guergabo -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  infra.nats:
    image: docker.io/nats:latest
    container_name: nats
    hostname: nats
    networks:
      basic-net:
        ipv4_address: 10.0.0.14
    ports:
      - "4222:4222"  
      - "8222:8222"
    command: [
      "--user=guergabo", 
      "--pass=password",
      "-js",                       
      "--store_dir=/data",
      "-m=8222"
    ]
    volumes:
      - nats_data:/data   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  infra.stripe-mock:
    image: docker.io/stripemock/stripe-mock:latest
    container_name: stripe-mock
    hostname: stripe-mock
    networks:
      basic-net:
        ipv4_address: 10.0.0.15
    ports:
      - "12111:12111" 
      - "12112:12112"
    command: [
      "-http-port=12111",
      "-https-port=12112"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12111/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  basic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  postgres_data:
  nats_data:
