name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test:
        description: 'Test name'
        required: false
        default: ''
        type: string

permissions:
  contents: read

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [
          { name: 'config', image: 'config' },
          { name: 'order', image: 'order' },
          { name: 'payment', image: 'payment' },
          { name: 'test-template', image: 'test-template' },
        ]

    outputs:
      ${{ matrix.image }}-digest: ${{ steps.store-digest.outputs.digest }}

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # (1) Add to your repo. 
        password: ${{ secrets.DOCKER_PAT }}      # (2) Add to your repo. 

    - name: Extract metadata (tags) for ${{ matrix.service.name }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: antithesishq/${{ matrix.service.image }} # TODO: update docker compose?? why not antithesishq?
        tags: |
          type=sha
          type=raw,value=v1
          antithesis

    - name: Build and push ${{ matrix.service.name }}
      id: build-push
      uses: docker/build-push-action@v5
      with: # might need to adjust context and file. 
        context: ./${{ matrix.service.name }}
        file: ./${{ matrix.service.name }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Store digest for ${{ matrix.service.name }}
      id: store-digest
      run: echo "digest=${{ steps.build-push.outputs.digest }}" >> $GITHUB_OUTPUT

  test: 
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Antithesis Tests
      uses: antithesishq/antithesis-trigger-action@main
      with:
        notebook_name: basic_test                    # (3) Update to your notebook. 
        tenant: ant.dogfood                          # (4) Update to your tenant.
        username: ${{ secrets.ANTITHESIS_USERNAME }} # (5) Add to your repo. 
        password: ${{ secrets.ANTITHESIS_PASSWORD }} # (6) Add to your repo. 
        github_token: ${{ secrets.GH_PAT }}          # (7) ...?
        ###########################################################################
        config_image: config@${{ needs.build.outputs["config-digest"] }}
        images: >-
          docker.io/antithesishq/order@${{ needs.build.outputs["order-digest"] }};
          docker.io/antithesishq/payment@${{ needs.build.outputs["payment-digest"] }};
          docker.io/antithesishq/test-template@${{ needs.build.outputs["test-template-digest"] }};
        ###########################################################################
        # TODO: other params like duration and email.
        description: "The CI run for ref - ${{ github.ref_name }} commit # ${{ github.sha }}"
        test_name:  ${{ inputs.test }}
        additional_parameters: |-
          custom.repo_name=${{github.repository}}
          custom.action_name = ${{github.action}}
          custom.actor = ${{ github.actor }}
