name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test:
      description: 'Test name'
      required: false
      default: ''
      type: string

permissions:
  contents: read

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [
          { name: 'config', image: 'config' },
          { name: 'order', image: 'order' },
          { name: 'payment', image: 'payment' }
          { name: 'test-template', image: 'test-template' },
        ]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        # TODO: swap out to push to antithesis repo. 
        # username: ${{ secrets.DOCKER_USERNAME }} # Add to your repo. 
        # password: ${{ secrets.DOCKER_PAT }}      # Add to your repo. 

    - name: Extract metadata (tags) for ${{ matrix.service.name }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: antithesishq/${{ matrix.service.image }} # TODO: update docker compose?? why antithesishq?
        tags: |
          type=sha
          type=raw,value=v1
          antithesis

    - name: Build and push ${{ matrix.service.name }}
      id: build-push
      uses: docker/build-push-action@v5
      with: # might need to adjust context and file. 
        context: ./${{ matrix.service.name }}
        file: ./${{ matrix.service.name }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  test: 
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Run Antithesis Tests
    #   uses: antithesishq/antithesis-trigger-action@main
    #   with:
    #     notebook_name: basic_test                    # Update to your notebook. 
    #     tenant: ant.dogfood                          # Update to your tenant.
    #     username: ${{ secrets.ANTITHESIS_USERNAME }} # Add to your repo. 
    #     password: ${{ secrets.ANTITHESIS_PASSWORD }} # Add to your repo. 
    #     github_token: ${{ secrets.GH_PAT }}          # ...?
    #     ###########################################################################
    #     config_image: config@${{ needs.build.outputs['build-push-config'] }}
    #     images: >-
    #       docker.io/antithesishq/order@${{ needs.build-and-test.outputs['build-push-control'] }};
    #       docker.io/antithesishq/payment@${{ needs.build.outputs['build-push-payment'] }};
    #       docker.io/antithesishq/test-template@${{ needs.build.outputs['build-push-test-template'] }};
    #     ###########################################################################
    #     # TODO: other params like duration and email.
    #     description: "The CI run for ref - ${{ github.ref_name }} commit # ${{ github.sha }}"
    #     test_name:  ${{ inputs.test }}
    #     additional_parameters: |-
    #       custom.repo_name=${{github.repository}}
    #       custom.action_name = ${{github.action}}
    #       custom.actor = ${{ github.actor }}
