name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test:
        description: 'Test name'
        required: false
        default: ''
        type: string

permissions:
  contents: read

jobs:
  build: 
    runs-on: ubuntu-latest
    outputs:
      config-digest: ${{ steps.build-config.outputs.digest }}
      order-digest: ${{ steps.build-order.outputs.digest }}
      payment-digest: ${{ steps.build-payment.outputs.digest }}
      test-template-digest: ${{ steps.build-test-template.outputs.digest }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # (1) Add to your repo. 
        password: ${{ secrets.DOCKER_PAT }}      # (2) Add to your repo. 

    # Config image
    - name: Extract metadata for config
      id: meta-config
      uses: docker/metadata-action@v5
      with:
        images: antithesishq/config
        tags: |
          type=sha
          type=raw,value=v1
          antithesis

    - name: Build and push config
      id: build-config
      uses: docker/build-push-action@v5
      with:
        context: ./config
        file: ./config/Dockerfile
        push: true
        tags: ${{ steps.meta-config.outputs.tags }}
        labels: ${{ steps.meta-config.outputs.labels }}

    # Order image 
    - name: Extract metadata for order
      id: meta-order
      uses: docker/metadata-action@v5
      with:
        images: antithesishq/order
        tags: |
          type=sha
          type=raw,value=v1
          antithesis

    - name: Build and push order
      id: build-order
      uses: docker/build-push-action@v5
      with:
        context: ./order
        file: ./order/Dockerfile
        push: true
        tags: ${{ steps.meta-order.outputs.tags }}
        labels: ${{ steps.meta-order.outputs.labels }}

    # Payment image
    - name: Extract metadata for payment
      id: meta-payment
      uses: docker/metadata-action@v5
      with:
        images: antithesishq/payment
        tags: |
          type=sha
          type=raw,value=v1
          antithesis

    - name: Build and push payment
      id: build-payment
      uses: docker/build-push-action@v5
      with:
        context: ./payment
        file: ./payment/Dockerfile
        push: true
        tags: ${{ steps.meta-payment.outputs.tags }}
        labels: ${{ steps.meta-payment.outputs.labels }}

    # Test template image
    - name: Extract metadata for test-template
      id: meta-test-template
      uses: docker/metadata-action@v5
      with:
        images: antithesishq/test-template
        tags: |
          type=sha
          type=raw,value=v1
          antithesis

    - name: Build and push test-template
      id: build-test-template
      uses: docker/build-push-action@v5
      with:
        context: ./test-template
        file: ./test-template/Dockerfile
        push: true
        tags: ${{ steps.meta-test-template.outputs.tags }}
        labels: ${{ steps.meta-test-template.outputs.labels }}

  test: 
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Antithesis Tests
      uses: antithesishq/antithesis-trigger-action@main
      with:
        notebook_name: basic_test                    # (3) Update to your notebook. 
        tenant: ant.dogfood                          # (4) Update to your tenant.
        username: ${{ secrets.ANTITHESIS_USERNAME }} # (5) Add to your repo. 
        password: ${{ secrets.ANTITHESIS_PASSWORD }} # (6) Add to your repo. 
        github_token: ${{ secrets.GH_PAT }}          # (7) ...?
        config_image: config@${{ needs.build.outputs.config-digest }}
        images: >-
          docker.io/antithesishq/order@${{ needs.build.outputs.order-digest }};
          docker.io/antithesishq/payment@${{ needs.build.outputs.payment-digest }};
          docker.io/antithesishq/test-template@${{ needs.build.outputs.test-template-digest }};
        description: "The CI run for ref - ${{ github.ref_name }} commit # ${{ github.sha }}"
        test_name: ${{ inputs.test }}
        additional_parameters: |-
          custom.repo_name=${{github.repository}}
          custom.action_name=${{github.action}}
          custom.actor=${{ github.actor }}
